services:
  db:
    image: mysql:8.0
    container_name: estoque_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque
      MYSQL_USER: estoque
      MYSQL_PASSWORD: estoque
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  
  api:
    build: .
    container_name: estoque_api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: estoque
      DB_PASS: estoque
      DB_NAME: estoque
      # opcional:
      # PORT: 3000
    ports:
      - "3000:3000"
    # Se você quiser DEV dentro do docker (hot reload), veja a seção "modo dev" abaixo

volumes:
  mysql_data:
